/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.xima.fc.form.expression.node;

import de.xima.fc.form.expression.enums.EChainType;
import de.xima.fc.form.expression.enums.EMethod;
import de.xima.fc.form.expression.grammar.ParseException;

public abstract class AFunctionCallNode extends SimpleNode {

	public final EChainType chainType;

	public AFunctionCallNode(final int id, final EChainType chainType) {
		super(id);
		this.chainType = chainType;
	}

	public final EChainType getChainType() {
		return chainType;
	}

	public abstract void init(EMethod method, String name) throws ParseException;

	public abstract String getMethodName();

}