/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.xima.fc.form.expression.node;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.exception.EvaluationException;
import de.xima.fc.form.expression.grammar.FormExpressionParser;
import de.xima.fc.form.expression.grammar.ParseException;
import de.xima.fc.form.expression.object.ALangObject;
import de.xima.fc.form.expression.util.EFunctionType;

public abstract class AFunctionCallNode extends MySimpleNode {

	public AFunctionCallNode(final int id) {
		super(id);
	}

	public AFunctionCallNode(final FormExpressionParser p, final int id) {
		super(p, id);
	}

	public abstract EFunctionType getType();

	public abstract ALangObject chain(final ALangObject thisContext, final IEvaluationContext ec)
			throws EvaluationException;

	public abstract void init(String name) throws ParseException;

}