/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.xima.fc.form.expression.node;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.grammar.FormExpressionParser;
import de.xima.fc.form.expression.grammar.ParseException;
import de.xima.fc.form.expression.object.ALangObject;
import de.xima.fc.form.expression.object.BooleanLangObject;

public class ASTBooleanNode extends MySimpleNode {

	private boolean booleanValue;

	public ASTBooleanNode(final int id) {
		super(id);
	}

	public ASTBooleanNode(final FormExpressionParser p, final int id) {
		super(p, id);
	}

	@Override
	public ALangObject evaluate(final IEvaluationContext fc) {
		return BooleanLangObject.create(booleanValue);
	}

	@Override
	public String toString() {
		return "BooleanNode(" + (booleanValue ? "true)" : "false)");
	}

	public void init(final boolean b) throws ParseException {
		booleanValue = b;
	}

}
/* JavaCC - OriginalChecksum=503be1ce8947242e29978502e565cd73 (do not edit this line) */
