/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.xima.fc.form.expression.node;

import de.xima.fc.form.expression.enums.EMethod;
import de.xima.fc.form.expression.exception.EvaluationException;
import de.xima.fc.form.expression.grammar.ParseException;
import de.xima.fc.form.expression.visitor.IFormExpressionParserVisitor;

public class ASTBooleanNode extends SimpleNode {

	private boolean booleanValue;

	public ASTBooleanNode(final int id) {
		super(id);
	}

	@Override
	public String toString() {
		return "BooleanNode(" + (booleanValue ? "true)" : "false)");
	}

	@Override
	public <R, T> R jjtAccept(final IFormExpressionParserVisitor<R, T> visitor, final T data) throws EvaluationException {
		return visitor.visit(this, data);
	}

	public void init(final EMethod method, final boolean b) throws ParseException {
		booleanValue = b;
		siblingMethod = method;
	}

	public boolean getBooleanValue() {
		return booleanValue;
	}

}
/* JavaCC - OriginalChecksum=503be1ce8947242e29978502e565cd73 (do not edit this line) */
