/* Generated By:JJTree: Do not edit this line. ASTFunctionArgument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.xima.fc.form.expression.node;



import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.error.EvaluationException;
import de.xima.fc.form.expression.grammar.FormExpressionParser;
import de.xima.fc.form.expression.object.ALangObject;

public class ASTFunctionArgument extends MySimpleNode {
	private MySimpleNode argument;

	public ASTFunctionArgument(final int id) {
		super(id);
	}

	public ASTFunctionArgument(final FormExpressionParser p, final int id) {
		super(p, id);
	}

	@Override
	public ALangObject evaluate(final IEvaluationContext ec) throws EvaluationException {
		return argument.evaluate(ec);
	}


}
/* JavaCC - OriginalChecksum=4f07e54f2396074b96c7911ebb2ad52a (do not edit this line) */
