/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.xima.fc.form.expression.node;

import java.math.BigDecimal;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.grammar.FormExpressionParser;
import de.xima.fc.form.expression.grammar.ParseException;
import de.xima.fc.form.expression.object.ALangObject;
import de.xima.fc.form.expression.object.NumberLangObject;

public class ASTNumberNode extends MySimpleNode {
	private BigDecimal value;


	public ASTNumberNode(final int id) {
		super(id);
	}

	public ASTNumberNode(final FormExpressionParser p, final int id) {
		super(p, id);
	}

	@Override
	public ALangObject evaluate(final IEvaluationContext fc) {
		return NumberLangObject.create(value);
	}

	public void init(final String string) throws ParseException {
		try {
			value = new BigDecimal(string, NumberLangObject.MATH_CONTEXT);
		}
		catch (final NumberFormatException e) {
			throw new ParseException("not a number: " + string);
		}
	}

	@Override
	public String toString() {
		return "NumberNode(" + value + ")";
	}

}
/* JavaCC - OriginalChecksum=503be1ce8947242e29978502e565cd73 (do not edit this line) */
