/* Generated By:JavaCC: Do not edit this line. FormExpressionParserTreeConstants.java Version 5.0 */
package de.xima.fc.form.expression.grammar;

@SuppressWarnings("all")
public interface FormExpressionParserTreeConstants
{
  public int JJTSTATEMENTLISTNODE = 0;
  public int JJTLOSNODE = 1;
  public int JJTVOID = 2;
  public int JJTSCOPEGLOBALNODE = 3;
  public int JJTSCOPEMANUALNODE = 4;
  public int JJTSCOPEEXTERNALNODE = 5;
  public int JJTVARIABLEDECLARATIONCLAUSENODE = 6;
  public int JJTFUNCTIONARGUMENTNODE = 7;
  public int JJTVARIABLETYPENODE = 8;
  public int JJTFUNCTIONCLAUSENODE = 9;
  public int JJTWITHCLAUSENODE = 10;
  public int JJTCONTINUECLAUSENODE = 11;
  public int JJTBREAKCLAUSENODE = 12;
  public int JJTRETURNCLAUSENODE = 13;
  public int JJTTHROWCLAUSENODE = 14;
  public int JJTSWITCHCLAUSENODE = 15;
  public int JJTTRYCLAUSENODE = 16;
  public int JJTDOWHILELOOPNODE = 17;
  public int JJTWHILELOOPNODE = 18;
  public int JJTFORLOOPNODE = 19;
  public int JJTIFCLAUSENODE = 20;
  public int JJTEMPTYNODE = 21;
  public int JJTASSIGNMENTEXPRESSIONNODE = 22;
  public int JJTTERNARYEXPRESSIONNODE = 23;
  public int JJTEXPRESSIONNODE = 24;
  public int JJTEQUALEXPRESSIONNODE = 25;
  public int JJTCOMPARISONEXPRESSIONNODE = 26;
  public int JJTUNARYEXPRESSIONNODE = 27;
  public int JJTPOSTUNARYEXPRESSIONNODE = 28;
  public int JJTPROPERTYEXPRESSIONNODE = 29;
  public int JJTDOTPROPERTYNODE = 30;
  public int JJTIDENTIFIERNAMENODE = 31;
  public int JJTARRAYNODE = 32;
  public int JJTPARENTHESISEXPRESSIONNODE = 33;
  public int JJTVARIABLENODE = 34;
  public int JJTNUMBERNODE = 35;
  public int JJTSTRINGNODE = 36;
  public int JJTSTRINGCHARACTERSNODE = 37;
  public int JJTHASHNODE = 38;
  public int JJTNULLNODE = 39;
  public int JJTBOOLEANNODE = 40;
  public int JJTLOGNODE = 41;
  public int JJTEXCEPTIONNODE = 42;
  public int JJTFUNCTIONNODE = 43;
  public int JJTREGEXNODE = 44;


  public String[] jjtNodeName = {
    "StatementListNode",
    "LosNode",
    "void",
    "ScopeGlobalNode",
    "ScopeManualNode",
    "ScopeExternalNode",
    "VariableDeclarationClauseNode",
    "FunctionArgumentNode",
    "VariableTypeNode",
    "FunctionClauseNode",
    "WithClauseNode",
    "ContinueClauseNode",
    "BreakClauseNode",
    "ReturnClauseNode",
    "ThrowClauseNode",
    "SwitchClauseNode",
    "TryClauseNode",
    "DoWhileLoopNode",
    "WhileLoopNode",
    "ForLoopNode",
    "IfClauseNode",
    "EmptyNode",
    "AssignmentExpressionNode",
    "TernaryExpressionNode",
    "ExpressionNode",
    "EqualExpressionNode",
    "ComparisonExpressionNode",
    "UnaryExpressionNode",
    "PostUnaryExpressionNode",
    "PropertyExpressionNode",
    "DotPropertyNode",
    "IdentifierNameNode",
    "ArrayNode",
    "ParenthesisExpressionNode",
    "VariableNode",
    "NumberNode",
    "StringNode",
    "StringCharactersNode",
    "HashNode",
    "NullNode",
    "BooleanNode",
    "LogNode",
    "ExceptionNode",
    "FunctionNode",
    "RegexNode",
  };
}
/* JavaCC - OriginalChecksum=3d44ba3f4743ba802e3fc5a7f1afec87 (do not edit this line) */
