package de.xima.fc.form.expression.iface.evaluate;

import javax.annotation.ParametersAreNonnullByDefault;

import de.xima.fc.form.expression.node.ASTArrayNode;
import de.xima.fc.form.expression.node.ASTAssignmentExpressionNode;
import de.xima.fc.form.expression.node.ASTBooleanNode;
import de.xima.fc.form.expression.node.ASTBreakClauseNode;
import de.xima.fc.form.expression.node.ASTComparisonExpressionNode;
import de.xima.fc.form.expression.node.ASTContinueClauseNode;
import de.xima.fc.form.expression.node.ASTDoWhileLoopNode;
import de.xima.fc.form.expression.node.ASTEmptyNode;
import de.xima.fc.form.expression.node.ASTEqualExpressionNode;
import de.xima.fc.form.expression.node.ASTExceptionNode;
import de.xima.fc.form.expression.node.ASTExpressionNode;
import de.xima.fc.form.expression.node.ASTForLoopNode;
import de.xima.fc.form.expression.node.ASTFunctionArgumentNode;
import de.xima.fc.form.expression.node.ASTFunctionClauseNode;
import de.xima.fc.form.expression.node.ASTFunctionNode;
import de.xima.fc.form.expression.node.ASTHashNode;
import de.xima.fc.form.expression.node.ASTIdentifierNameNode;
import de.xima.fc.form.expression.node.ASTIfClauseNode;
import de.xima.fc.form.expression.node.ASTLogNode;
import de.xima.fc.form.expression.node.ASTLosNode;
import de.xima.fc.form.expression.node.ASTNullNode;
import de.xima.fc.form.expression.node.ASTNumberNode;
import de.xima.fc.form.expression.node.ASTParenthesisExpressionNode;
import de.xima.fc.form.expression.node.ASTPostUnaryExpressionNode;
import de.xima.fc.form.expression.node.ASTPropertyExpressionNode;
import de.xima.fc.form.expression.node.ASTRegexNode;
import de.xima.fc.form.expression.node.ASTReturnClauseNode;
import de.xima.fc.form.expression.node.ASTScopeExternalNode;
import de.xima.fc.form.expression.node.ASTScopeGlobalNode;
import de.xima.fc.form.expression.node.ASTScopeManualNode;
import de.xima.fc.form.expression.node.ASTStatementListNode;
import de.xima.fc.form.expression.node.ASTStringCharactersNode;
import de.xima.fc.form.expression.node.ASTStringNode;
import de.xima.fc.form.expression.node.ASTSwitchClauseNode;
import de.xima.fc.form.expression.node.ASTTernaryExpressionNode;
import de.xima.fc.form.expression.node.ASTThrowClauseNode;
import de.xima.fc.form.expression.node.ASTTryClauseNode;
import de.xima.fc.form.expression.node.ASTUnaryExpressionNode;
import de.xima.fc.form.expression.node.ASTVariableDeclarationClauseNode;
import de.xima.fc.form.expression.node.ASTVariableNode;
import de.xima.fc.form.expression.node.ASTVariableTypeNode;
import de.xima.fc.form.expression.node.ASTWhileLoopNode;
import de.xima.fc.form.expression.node.ASTWithClauseNode;

@ParametersAreNonnullByDefault
public interface IFormExpressionReturnVoidVisitor<R,E extends Throwable>
{
	public R visit(ASTExpressionNode node) throws E;
	public R visit(ASTAssignmentExpressionNode node) throws E;
	public R visit(ASTNumberNode node) throws E;
	public R visit(ASTArrayNode node) throws E;
	public R visit(ASTHashNode node) throws E;
	public R visit(ASTNullNode node) throws E;
	public R visit(ASTBooleanNode node) throws E;
	public R visit(ASTVariableNode node) throws E;
	public R visit(ASTStringNode node) throws E;
	public R visit(ASTStatementListNode node) throws E;
	public R visit(ASTIfClauseNode node) throws E;
	public R visit(ASTForLoopNode node) throws E;
	public R visit(ASTWhileLoopNode node) throws E;
	public R visit(ASTTryClauseNode node) throws E;
	public R visit(ASTSwitchClauseNode node) throws E;
	public R visit(ASTDoWhileLoopNode node) throws E;
	public R visit(ASTExceptionNode node) throws E;
	public R visit(ASTThrowClauseNode node) throws E;
	public R visit(ASTBreakClauseNode node) throws E;
	public R visit(ASTContinueClauseNode node) throws E;
	public R visit(ASTReturnClauseNode node) throws E;
	public R visit(ASTLogNode node) throws E;
	public R visit(ASTFunctionNode node) throws E;
	public R visit(ASTUnaryExpressionNode node) throws E;
	public R visit(ASTPropertyExpressionNode node) throws E;
	public R visit(ASTIdentifierNameNode node) throws E;
	public R visit(ASTWithClauseNode node) throws E;
	public R visit(ASTFunctionClauseNode node) throws E;
	public R visit(ASTEmptyNode node) throws E;
	public R visit(ASTLosNode node) throws E;
	public R visit(ASTRegexNode node) throws E;
	public R visit(ASTTernaryExpressionNode node) throws E;
	public R visit(ASTParenthesisExpressionNode node) throws E;
	public R visit(ASTEqualExpressionNode node) throws E;
	public R visit(ASTPostUnaryExpressionNode node) throws E;
	public R visit(ASTComparisonExpressionNode node) throws E;
	public R visit(ASTScopeExternalNode node) throws E;
	public R visit(ASTVariableDeclarationClauseNode node) throws E;
	public R visit(ASTScopeManualNode node) throws E;
	public R visit(ASTScopeGlobalNode node) throws E;
	public R visit(ASTVariableTypeNode node) throws E;
	public R visit(ASTFunctionArgumentNode node) throws E;
	public R visit(ASTStringCharactersNode node) throws E;
}
