/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.error;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.object.ALangObject;

/**
 * This exception is thrown when an object is coerced to another type
 * and the object cannot be coerced to that type.
 *
 */
public class CoercionException extends EvaluationException {

	private static final long serialVersionUID = 1L;

	public CoercionException(final ALangObject from, final ALangObject.Type to, final IEvaluationContext ec) {
		super(ec, "Object " + from.inspect() + " cannot be coerced to " + to.clazz.getSimpleName());
		this.from = from;
		this.to = to;
	}

	public final ALangObject from;
	public final ALangObject.Type to;
}
