/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.object.ALangObject;
import de.xima.fc.form.expression.util.CmnCnst;

/**
 * This exception is thrown when an object is coerced to another type
 * and the object cannot be coerced to that type.
 *
 */
public class CoercionException extends CatchableEvaluationException {

	private static final long serialVersionUID = 1L;

	public CoercionException(final ALangObject from, final ALangObject.Type to, final IEvaluationContext ec) {
		super(ec, String.format(CmnCnst.Error.COERCION, from.toString(), from.getType(), to));
		this.from = from;
		this.to = to;
	}

	public final ALangObject from;
	public final ALangObject.Type to;
}
