/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

/**
 * This exception is thrown when an object is coerced to another type
 * and the object cannot be coerced to that type.
 *
 */
public class CustomRuntimeException extends EvaluationException {

	private static final long serialVersionUID = 1L;

	public CustomRuntimeException(final String message) {
		super(message);
		this.message = message;
	}

	public final String message;
}
