/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.util.CmnCnst;

/**
 * This exception is thrown by a throw block .
 */
public class CustomRuntimeException extends CatchableEvaluationException {

	private static final long serialVersionUID = 1L;

	public CustomRuntimeException(final String message, final IEvaluationContext ec) {
		super(ec, String.format(CmnCnst.Error.CUSTOM_RUNTIME_EXCEPTION,message));
		this.message = message;
	}

	public final String message;
}
