/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import javax.annotation.Nonnull;

import de.xima.fc.form.expression.iface.context.IEvaluationContext;
import de.xima.fc.form.expression.object.ALangObject;

/**
 * This exception is thrown a number is divided by zero.
 */
public class DivisionByZeroException extends IllegalDividendException {

	private static final long serialVersionUID = 1L;

	public DivisionByZeroException(@Nonnull final ALangObject divisor, @Nonnull final ALangObject dividend, final int index, @Nonnull final IEvaluationContext ec) {
		super(divisor, dividend, index, ec);
	}
}
