/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.context.INamedFunction;
import de.xima.fc.form.expression.object.ALangObject;

/**
 * This exception is thrown when an object support the division
 * operator, but not with a certain operand.
 *
 */
public class IllegalArgumentValueException extends EvaluationException {

	private static final long serialVersionUID = 1L;

	public IllegalArgumentValueException(final INamedFunction<?> function, final String functionName, final ALangObject thisContext, final ALangObject argument, final int index, final IEvaluationContext ec) {
		super(ec, "Illegal value " + thisContext.inspect() + " for argument " + index + " of function " + functionName + ": " + argument.inspect());
		this.functionName = functionName;
		this.thisContext = thisContext;
		this.index = index;
		this.argument = argument;
		this.function = function;
	}

	public IllegalArgumentValueException(final String functionName, final ALangObject thisContext, final ALangObject argument, final int index, final IEvaluationContext ec) {
		this(null, functionName, thisContext, argument, index, ec);
	}

	public IllegalArgumentValueException(final INamedFunction<?> function, final ALangObject thisContext, final ALangObject argument, final int index, final IEvaluationContext ec) {
		this(function, function.getName(), thisContext, argument, index, ec);
	}

	public final ALangObject thisContext;
	public final ALangObject argument;
	public final int index;
	public final String functionName;
	public final INamedFunction<?> function;
}
