/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import de.xima.fc.form.expression.object.ALangObject;

/**
 * This exception is thrown when an object is coerced to another type
 * and the object cannot be coerced to that type.
 *
 */
public class IterationNotSupportedException extends EvaluationException {

	private static final long serialVersionUID = 1L;

	public IterationNotSupportedException(final ALangObject thisContext) {
		super("Object " + thisContext.getType() + " does not support iteration : " + thisContext);
		this.thisContext = thisContext;
	}

	public final ALangObject thisContext;
}
