/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.object.ALangObject;

/**
 * This exception is thrown when an object is coerced to another type
 * and the object cannot be coerced to that type.
 *
 */
public class IterationNotSupportedException extends CatchableEvaluationException {

	private static final long serialVersionUID = 1L;

	public IterationNotSupportedException(final ALangObject thisContext, final IEvaluationContext ec) {
		super(ec, String.format("Object <%s> of type %s does not support iteration.", thisContext.toString(), thisContext.getType()));
		this.thisContext = thisContext;
	}

	public final ALangObject thisContext;
}
