/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.object.ALangObject;

public class NoSuchAttrAssignerException extends NoSuchFunctionException {
	private static final long serialVersionUID = 1L;

	public NoSuchAttrAssignerException(final String name, final IEvaluationContext ec) {
		super("attribute assigner", name, ec);
	}

	public NoSuchAttrAssignerException(final String name, final boolean accessedViaDot, final IEvaluationContext ec) {
		super(accessedViaDot ? "dot attribute assigner" : "bracket attribute assigner", name, ec);
	}

	public NoSuchAttrAssignerException(final String name, final ALangObject thisContext, final IEvaluationContext ec) {
		super("attribute assigner", name, thisContext, ec);
	}

	public NoSuchAttrAssignerException(final String name, final ALangObject thisContext, final boolean accessedViaDot, final IEvaluationContext ec) {
		super(accessedViaDot ? "dot attribute assigner" : "bracket attribute assigner", name, thisContext, ec);
	}
}
