/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.object.ALangObject;

public class NoSuchAttrAccessorException extends NoSuchFunctionException {
	private static final long serialVersionUID = 1L;

	public NoSuchAttrAccessorException(final String name, final IEvaluationContext ec) {
		super("attribute accessor", name, ec);
	}

	public NoSuchAttrAccessorException(final String name, final boolean accessedViaDot, final IEvaluationContext ec) {
		super(accessedViaDot ? "dot attribute accessor" : "bracket attribute accessor", name, ec);
	}

	public NoSuchAttrAccessorException(final String name, final ALangObject thisContext, final IEvaluationContext ec) {
		super("attribute accessor", name, thisContext, ec);
	}

	public NoSuchAttrAccessorException(final String name, final ALangObject thisContext, final boolean accessedViaDot, final IEvaluationContext ec) {
		super(accessedViaDot ? "dot attribute accessor" : "bracket attribute accessor", name, thisContext, ec);
	}

}
