/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 5.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package de.xima.fc.form.expression.exception;

import javax.annotation.Nonnull;

import de.xima.fc.form.expression.context.IEvaluationContext;
import de.xima.fc.form.expression.object.ALangObject;
import de.xima.fc.form.expression.util.CmnCnst;

public class NoSuchAttrAssignerException extends NoSuchFunctionException {
	private static final long serialVersionUID = 1L;

	public NoSuchAttrAssignerException(@Nonnull final String name, @Nonnull final IEvaluationContext ec) {
		super(CmnCnst.NAME_ATTRIBUTE_ASSIGNER, name, ec);
	}

	public NoSuchAttrAssignerException(@Nonnull final String name, final boolean accessedViaDot,
			@Nonnull final IEvaluationContext ec) {
		super(accessedViaDot ? CmnCnst.NAME_DOT_ATTRIBUTE_ASSIGNER : CmnCnst.NAME_BRACKET_ATTRIBUTE_ASSIGNER, name, ec);
	}

	public NoSuchAttrAssignerException(@Nonnull final String name, @Nonnull final ALangObject thisContext,
			@Nonnull final IEvaluationContext ec) {
		super(CmnCnst.NAME_ATTRIBUTE_ASSIGNER, name, thisContext, ec);
	}

	public NoSuchAttrAssignerException(@Nonnull final String name, @Nonnull final ALangObject thisContext,
			final boolean accessedViaDot, @Nonnull final IEvaluationContext ec) {
		super(accessedViaDot ? CmnCnst.NAME_DOT_ATTRIBUTE_ASSIGNER : CmnCnst.NAME_BRACKET_ATTRIBUTE_ASSIGNER, name,
				thisContext, ec);
	}
}
