package de.xima.fc.form.expression.enums;

public enum ESeverityOption {
	TREAT_SCOPED_FUNCTION_OUTSIDE_HEADER_AS_ERROR,
	TREAT_MISSING_DECLARATION_AS_ERROR,
	TREAT_MISSING_REQUIRE_SCOPE_AS_ERROR(),
	TREAT_MISSING_SCOPE_DECLARATION_AS_ERROR,
	TREAT_UNMATCHING_SWITCH_TYPE_AS_ERROR,
	TREAT_UNREACHABLE_CODE_AS_ERROR,
	TREAT_MISSING_EXPLICIT_RETURN_AS_ERROR,
	TREAT_UNMATCHING_VARIABLE_TYPES_AS_ERROR
	;
}